### ISSUE TITLE
Fix rpm installer

### ISSUE THREAD

**Issue by pablgonz** [chiva/Platex#1]
Hi, great job you've done the "rpm" can not install quite right in versions 19-20 fedora package, unfortunately. I have tried to rebuild the package using the line:
$ sudo bash -c "wget https://raw.github.com/gist/1427486/build-linux.sh && bash build-linux.sh"
but throws an error not finding the file. Could you fix this problem or let available the file src rpm (Platex.spec) to rebuild it. 
greetings 
Pablo

**Comment by chiva** [comment]
Hi Pablo,

Could you specify what is the problem with the installation?
Any errors? Does it finish installing correctly? Is the problem appearing when trying to start the program?

## How to fix the build script

It seems that github changed the url to acces raw gists, use the following url:
https://gist.githubusercontent.com/chiva/1427486/raw/build-linux.sh

You will have to update the library versions so that it dowloads the available ones (old ones are usually removed periodically)

``` Shell
PYQWT=5.2.0
ARDUINO=1.0.1
CXFREEZE=4.2.3
```

In the following it seems I hardcoded the revision number in the qwt folder (5.2) which should be updated to the latest one.

``` Shell
python configure.py -Q ../qwt-5.2 --qt4 --disable-numarray --disable-numeric --disable-numpy
```

It may need a few more fixes as folder names and paths may have changed in new versions of the libraries.
